---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: instance
    image: ghcr.io/docker-hub-tm/ansible-test/${MOLECULE_DISTRO:-centos8}:latest
    command: /sbin/init
    privileged: True
provisioner:
  name: ansible
  config_options:
    defaults:
      callback_whitelist: ansible.posix.profile_tasks
  connection_options:
    aws_access_key_id: ${AWS_ACCESS_KEY_ID}
    aws_secret_access_key: ${AWS_SECRET_ACCESS_KEY}
    aws_region: ${AWS_REGION}
verifier:
  name: ansible
scenario:
  test_sequence:
    - syntax
    - dependency
    - create
    - prepare
    - converge
    - idempotence
    - verify
